const { Model, DataTypes } = require("sequelize");
const sequelize = require("../config/db");
const { verify } = require("jsonwebtoken");

const WifeTextValue = sequelize.define(
  "WifeTextValue",
  {
    para: DataTypes.STRING,
    prep_weight: DataTypes.DECIMAL(5, 2),
    bmi: DataTypes.DECIMAL(5, 2),
    p: DataTypes.STRING,
    a: DataTypes.STRING,
    last: DataTypes.STRING,
    lmp: DataTypes.DATE,
    edc: DataTypes.DATE,
    ga: DataTypes.STRING,
    ma_detail: DataTypes.STRING,
    hr_detail: DataTypes.STRING,
    lab_wife_result_id: DataTypes.INTEGER,
    pcr_wife_text: DataTypes.STRING,
    cordo_text: DataTypes.STRING,
    cordo_other_text: DataTypes.STRING,
    am_detail_1: DataTypes.STRING,
    am_detail_2: DataTypes.STRING,
    am_detail_3: DataTypes.STRING,
    td_num: DataTypes.STRING,
    td_last_date: DataTypes.DATE,
    td_forget_date: DataTypes.STRING,
    vaccine_detail_1: DataTypes.STRING,
    vaccine_detail_2: DataTypes.STRING,
    vaccine_detail_3: DataTypes.STRING,
    vaccine_date_1: DataTypes.DATE,
    vaccine_date_2: DataTypes.DATE,
    vaccine_date_3: DataTypes.DATE,
    tdap_round_1: DataTypes.DATE,
    tdap_round_2: DataTypes.DATE,
    tdap_round_3: DataTypes.DATE,
    iip_date: DataTypes.DATE,
    lab_2: DataTypes.DATE,
    vdrl_2: { type: DataTypes.STRING(30), allowNull: true },
    ppr_wife_2: DataTypes.STRING,
    tpha_wife_2: DataTypes.STRING,
    treatment_detail_wife_2: DataTypes.STRING,
    vac_lab_date_1_wife_2: DataTypes.DATE,
    vac_lab_date_2_wife_2: DataTypes.DATE,
    vac_lab_date_3_wife_2: DataTypes.DATE,
    hct: { type: DataTypes.STRING(30), allowNull: true },
    hiv: { type: DataTypes.STRING(30), allowNull: true },
    bti_1_date: DataTypes.DATE,
    bti_2_date: DataTypes.DATE,
    birads_detail_1: DataTypes.STRING,
    birads_detail_2: DataTypes.STRING,
    birads_detail_3: DataTypes.STRING,
    cbe_result: DataTypes.STRING,
    per_os_detail_1: DataTypes.STRING,
    per_os_detail_2: DataTypes.STRING,
    per_os_detail_3: DataTypes.STRING,
    per_os_detail_4: DataTypes.STRING,
    per_os_detail_5: DataTypes.STRING,
  },
  {
    sequelize,
    modelName: "WifeTextValue",
    tableName: "wife_text_value", // ต้องตรงกับชื่อ table จริง
  }
);

module.exports = WifeTextValue;
